### ISSUE TITLE
触摸板无法使用

### ISSUE THREAD

**Issue by htsait4113** [Zero-zer0/Matebook_13_14_2020_Hackintosh_OpenCore#10]
matebook D 14 2020版，已更新v1.7，触摸板无法使用，蓝牙连接鼠标连接不上

**Comment by llkhs** [comment]
你看清楚了这个库不支持matebook D 的

**Comment by htsait4113** [comment]
> 你看清楚了这个库不支持matebook D 的

我晕，我一直以为这个是支持D的，我现在用的就是这个EFI，我说触摸板怎么一直没法用，不过总体来说，用这个EFI还是能凑合用的
