### ISSUE TITLE
请问matebook x pro 2020版本可以使用吗？

### ISSUE THREAD

**Issue by kdzmwl** [Zero-zer0/Matebook_13_14_2020_Hackintosh_OpenCore#5]
如题，不知有没有尝试过的大佬。

**Comment by Zero-zer0** [comment]
抱歉，按照以往华为Matebook系列开发的情况来看，本套配置无法在X Pro 2020上正常使用。

从ACPI的配置上来看，Magicbook/Matebook D同属一个系列，定位中低端；Matebook 13/14属于一个系列，定位中高端；而Matebook X/X Pro是的一个系列，定位高端。它们在ACPI上有极大的差异，特别表现在X Pro系列的ACPI存在一系列的验证函数保证安全性。

从以往的经验来看，Matebook X Pro 2020大概率是2019挤牙膏升级而来，2019款的配置应该具有一定的意义。
- X Pro系列在电池的ACPI上需要专门修补，而且较为复杂，你可以参考：
    - [iStar](https://github.com/XStar-Dev)的电池补丁教程： [link](https://xstar-dev.github.io/hackintosh_advanced/Guide_For_Battery_Hotpatch.html)
    - 以及 [iStar](https://github.com/XStar-Dev)根据[laozhiang](https://github.com/laozhiang)的配置移植的[电池热补丁](https://github.com/GZXiaoBai/Hackintosh-Battery-Hotpatch/blob/master/HUAWEI/SSDT-HWBT-MagicBook%20X%20Pro%202019.aml)

- X Pro 2019的配置：
    - 加群:`527454189` . 这里有X Pro 2019的全hotpatch配置可供参考
    - [laozhiang](https://github.com/laozhiang) 的X Pro仓库，是基于DSDT的修补的一套配置

由于Acidanthera表示现阶段不会针对10代平台作出特别的研究，所以Comet Lake系列只能自行摸索。
你仍然可以参考本仓库、[小新Pro13的仓库](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh)来制作适合自己的配置。

祝好运！
