### ISSUE TITLE
matebook 13 2019 I7版本 触摸板找不到

### ISSUE THREAD

**Issue by ske1996** [Zero-zer0/Matebook_13_14_2020_Hackintosh_OpenCore#9]
在系统偏好设置里点击触摸板后截图如下
<img width="657" alt="截屏0002-06-03 19 27 33" src="https://user-images.githubusercontent.com/63181546/83626388-4b1a0b00-a5d0-11ea-9ddc-4af7f9816a7a.png">

**Comment by Zero-zer0** [comment]
本仓库没有为Matebook 13 2019做适配，请使用：[Edoard001](https://github.com/Edoardo001)制作的配置：https://github.com/Edoardo001/Matebook-13-Hackintosh
